name: Test JS Env
version: 0.0.4
slug: test-js-env
description: Des tests bro
arch:
  - aarch64
ports:
  3000/tcp: 8888
ports_description:
  3000/tcp: app node
apparmor: false
init: false
schema:
  MY_VAR: str
options:
  MY_VAR: "DEFAULT_OPTIONS"
environment:
  MY_VAR: "DEFAULT 2"
