name: Pairdrop
version: 1.10.7
slug: pairdrop
description:
  Pairdrop is a AirDrop-like progressive web app that transfers files between
  browsers. Data is transfered between machines on the same IP subnet / LAN network
  using WebRTC with traffic being encrypted in transit.
arch:
  - aarch64
  - amd64
url: https://github.com/schlagmichdoch/pairdrop
webui: "[PROTO:ssl]://[HOST]:[PORT:3000]"
ports:
  3000/tcp: 3003
ports_description:
  3000/tcp: web interface
apparmor: true
init: false
