name: Homepage
version: 0.9.11
slug: homepage
description:
  A modern, fully static, fast, secure fully proxied, highly customizable application dashboard
  with integrations for over 100 services and translations into multiple languages.
  Easily configured via YAML files or through docker label discovery.
arch:
  - aarch64
  - amd64
url: https://gethomepage.dev
webui: "[PROTO:ssl]://[HOST]:[PORT:3000]"
ports:
  3000/tcp: 3030
map:
  - addon_config:rw
ports_description:
  3000/tcp: web interface
apparmor: true
init: false
