name: Jellystat
version: 1.1.0
slug: jellystat
description: Jellystat is a free and open source Statistics App for Jellyfin!
arch:
  - aarch64
  - amd64
  - armv7
url: https://github.com/CyferShepard/Jellystat
webui: "[PROTO:ssl]://[HOST]:[PORT:3000]"
ports:
  3000/tcp: 3031
map:
  - addon_config:rw
ports_description:
  3000/tcp: web interface
options:
  POSTGRES_USER: postgres
  POSTGRES_IP: homeassistant.local
  POSTGRES_PORT: 5432
schema:
  POSTGRES_USER: "str?"
  POSTGRES_PASSWORD: "str"
  POSTGRES_IP: "str?"
  POSTGRES_PORT: "int?"
  JWT_SECRET: "str"
apparmor: true
init: false
