name: Reiverr
version: 0.8.1
slug: reiverr
description:
  Reiverr test by benio
arch:
  - aarch64
  - amd64
url: https://github.com/aleksilassila/reiverr
webui: "[PROTO:ssl]://[HOST]:[PORT:9494]"
ports:
  9494/tcp: 9494
ports_description:
  9494/tcp: web interface
apparmor: false
init: false
startup: services
map:
  - config:rw
  - backup:rw
  - share:rw
  - ssl:ro
  - media:rw
