version: '3.8'

name: reiverr

services:
  reiverr-frontend:
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    build:
      context: .
      target: development
    ports:
      - 5173:5173
