name: "Cron & bash boilerplate"
description: "Add-on to run bash script with cron"
version: "1.0.0"
slug: "cron_bash_boilerplate"
init: false
map:
  - config:rw
  - share:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  isLeap: false
  year: 2017
schema:
  isLeap: bool
  name: "str?"
  year: int
startup: services
